import { UnitDefinition } from '../../engine/core/types';

export const ELF_UNITS: UnitDefinition[] = [
  // ── TIER I ──
  {
    id: 'e1_cazadora',
    name: 'Cazadora del Claro',
    faction: 'ELF',
    tier: 1,
    costGold: 3,
    maxHp: 4,
    move: 4,
    meleeDice: 1,
    rangedDice: 2,
    ascRequired: 3,
    cycleAffinity: 'SUN',
    goodTerrain: 'FOREST',
    badTerrain: 'CITY',
    traits: [{
      id: 'emboscada_forestal',
      name: 'Emboscada forestal',
      description: 'Desde Bosque: 1 dado ranged -> ventaja.',
      trigger: 'ON_BUILD_ATTACK_DICE_POOL',
      config: { requireTerrain: 'FOREST', mode: 'RANGED', advantageDice: 1 },
    }],
    evolvesTo: ['e5_ojo', 'e8_cantora'],
  },
  {
    id: 'e2_corredor',
    name: 'Corredor Silvano',
    faction: 'ELF',
    tier: 1,
    costGold: 3,
    maxHp: 3,
    move: 5,
    meleeDice: 1,
    rangedDice: 1,
    ascRequired: 4,
    cycleAffinity: 'SUN',
    goodTerrain: 'FOREST',
    badTerrain: 'FORTRESS',
    traits: [{
      id: 'sendero_silvano',
      name: 'Sendero silvano',
      description: 'El primer Bosque cuesta 1 en vez de 2.',
      trigger: 'ON_MOVE_COST_QUERY',
      config: { terrain: 'FOREST', reducedCost: 1, firstOnly: true },
    }],
    evolvesTo: ['e6_danzante', 'e5_ojo'],
  },
  {
    id: 'e3_guardian',
    name: 'Guardián Raíz',
    faction: 'ELF',
    tier: 1,
    costGold: 4,
    maxHp: 6,
    move: 2,
    meleeDice: 2,
    rangedDice: 0,
    ascRequired: 4,
    cycleAffinity: 'SUN',
    goodTerrain: 'FOREST',
    badTerrain: 'CITY',
    traits: [{
      id: 'raices_profundas',
      name: 'Raíces profundas',
      description: 'En Bosque: 1 dado melee -> ventaja.',
      trigger: 'ON_BUILD_ATTACK_DICE_POOL',
      config: { requireTerrain: 'FOREST', mode: 'MELEE', advantageDice: 1 },
    }],
    evolvesTo: ['e7_anciano', 'e8_cantora'],
  },
  {
    id: 'e4_oraculo',
    name: 'Oráculo del Rocío',
    faction: 'ELF',
    tier: 1,
    costGold: 2,
    maxHp: 3,
    move: 3,
    meleeDice: 0,
    rangedDice: 2,
    ascRequired: 3,
    cycleAffinity: 'SUN',
    goodTerrain: 'FOREST',
    badTerrain: 'HILL',
    traits: [{
      id: 'vision_quieta',
      name: 'Visión quieta',
      description: 'Si no se movió: 1 dado ranged -> ventaja.',
      trigger: 'ON_BUILD_ATTACK_DICE_POOL',
      config: { requireNoMove: true, mode: 'RANGED', advantageDice: 1 },
    }],
    evolvesTo: ['e8_cantora', 'e5_ojo'],
  },

  // ── TIER II ──
  {
    id: 'e5_ojo',
    name: 'Ojo del Dosel',
    faction: 'ELF',
    tier: 2,
    maxHp: 4,
    move: 4,
    meleeDice: 1,
    rangedDice: 3,
    ascRequired: 4,
    cycleAffinity: 'SUN',
    goodTerrain: 'FOREST',
    badTerrain: 'FORTRESS',
    traits: [{
      id: 'ojo_forestal',
      name: 'Ojo forestal',
      description: 'Desde Bosque o si no se movió: 1 dado ranged -> ventaja.',
      trigger: 'ON_BUILD_ATTACK_DICE_POOL',
      config: { requireTerrainOrNoMove: true, terrain: 'FOREST', mode: 'RANGED', advantageDice: 1 },
    }],
    evolvesTo: ['e9_arquera'],
  },
  {
    id: 'e6_danzante',
    name: 'Danzante del Alba',
    faction: 'ELF',
    tier: 2,
    maxHp: 5,
    move: 5,
    meleeDice: 2,
    rangedDice: 1,
    ascRequired: 4,
    cycleAffinity: 'SUN',
    goodTerrain: 'FOREST',
    badTerrain: 'FORTRESS',
    traits: [{
      id: 'danza_del_alba',
      name: 'Danza del alba',
      description: 'Tras infligir daño: mueve 1 hex (ignora Traba).',
      trigger: 'ON_AFTER_DAMAGE_APPLIED',
      config: { requireDamage: true, moveHexes: 1, ignoresEngagement: true },
    }],
    evolvesTo: ['e10_avatar'],
  },
  {
    id: 'e7_anciano',
    name: 'Anciano de Corteza',
    faction: 'ELF',
    tier: 2,
    maxHp: 8,
    move: 2,
    meleeDice: 3,
    rangedDice: 0,
    ascRequired: 5,
    cycleAffinity: 'SUN',
    goodTerrain: 'FOREST',
    badTerrain: 'CITY',
    traits: [{
      id: 'corteza_ancestral',
      name: 'Corteza ancestral',
      description: 'Primer daño de cada ronda reducido en 1.',
      trigger: 'ON_DAMAGE_RECEIVED',
      config: { damageReduction: 1, perRound: true },
    }],
    evolvesTo: ['e10_avatar'],
  },
  {
    id: 'e8_cantora',
    name: 'Cantora de Rocío',
    faction: 'ELF',
    tier: 2,
    maxHp: 4,
    move: 4,
    meleeDice: 1,
    rangedDice: 2,
    ascRequired: 4,
    cycleAffinity: 'SUN',
    goodTerrain: 'FOREST',
    badTerrain: 'HILL',
    traits: [{
      id: 'canto_curativo',
      name: 'Canto curativo',
      description: 'Si no atacó: cura 1 HP a aliado a 1 hex.',
      trigger: 'ON_ACTIVATION_END',
      config: { requireNoAttack: true, healAmount: 1, range: 1, targetAlly: true },
    }],
    evolvesTo: ['e9_arquera'],
  },

  // ── TIER III ──
  {
    id: 'e9_arquera',
    name: 'Arquera Astral',
    faction: 'ELF',
    tier: 3,
    maxHp: 5,
    move: 4,
    meleeDice: 1,
    rangedDice: 4,
    cycleAffinity: 'SUN',
    goodTerrain: 'FOREST',
    badTerrain: 'FORTRESS',
    traits: [{
      id: 'disparo_astral',
      name: 'Disparo astral',
      description: 'Primer ataque ranged de la ronda: hasta 2 dados -> ventaja.',
      trigger: 'ON_BUILD_ATTACK_DICE_POOL',
      config: { firstAttackOnly: true, mode: 'RANGED', advantageDice: 2 },
    }],
  },
  {
    id: 'e10_avatar',
    name: 'Avatar del Bosque',
    faction: 'ELF',
    tier: 3,
    maxHp: 9,
    move: 3,
    meleeDice: 4,
    rangedDice: 0,
    cycleAffinity: 'SUN',
    goodTerrain: 'FOREST',
    badTerrain: 'CITY',
    traits: [{
      id: 'raices_atrapantes',
      name: 'Raíces atrapantes',
      description: 'Los enemigos adyacentes no pueden abandonar su adyacencia.',
      trigger: 'ON_ACTIVATION_START',
      config: { auraEngagement: true },
    }],
  },
];
