import { UnitDefinition } from '../../engine/core/types';

export const HUMAN_UNITS: UnitDefinition[] = [
  // ── TIER I ──
  {
    id: 'h1_lancero',
    name: 'Lancero de la Marca',
    faction: 'HUMAN',
    tier: 1,
    costGold: 2,
    maxHp: 5,
    move: 3,
    meleeDice: 2,
    rangedDice: 0,
    ascRequired: 3,
    cycleAffinity: 'SUN',
    goodTerrain: 'CITY',
    badTerrain: 'FOREST',
    traits: [{
      id: 'guardia_cerrada',
      name: 'Guardia cerrada',
      description: 'Si no se movió, 1 dado melee -> ventaja.',
      trigger: 'ON_BUILD_ATTACK_DICE_POOL',
      config: { requireNoMove: true, mode: 'MELEE', advantageDice: 1 },
    }],
    evolvesTo: ['h5_defensor', 'h6_abanderado'],
  },
  {
    id: 'h2_duelista',
    name: 'Duelista de Sal',
    faction: 'HUMAN',
    tier: 1,
    costGold: 2,
    maxHp: 4,
    move: 4,
    meleeDice: 2,
    rangedDice: 0,
    ascRequired: 4,
    cycleAffinity: 'SUN',
    goodTerrain: 'CITY',
    badTerrain: 'HILL',
    traits: [{
      id: 'repliegue',
      name: 'Repliegue',
      description: 'Si inflige daño melee, mueve 1 hex (ignora Traba).',
      trigger: 'ON_AFTER_DAMAGE_APPLIED',
      config: { requireDamage: true, mode: 'MELEE', moveHexes: 1, ignoresEngagement: true },
    }],
    evolvesTo: ['h6_abanderado', 'h8_caballero'],
  },
  {
    id: 'h3_ballestero',
    name: 'Ballestero de Muralla',
    faction: 'HUMAN',
    tier: 1,
    costGold: 3,
    maxHp: 3,
    move: 2,
    meleeDice: 1,
    rangedDice: 2,
    ascRequired: 3,
    cycleAffinity: 'SUN',
    goodTerrain: 'FORTRESS',
    badTerrain: 'FOREST',
    traits: [{
      id: 'puesto_fijo',
      name: 'Puesto fijo',
      description: 'Si no se movió, 1 dado ranged -> ventaja.',
      trigger: 'ON_BUILD_ATTACK_DICE_POOL',
      config: { requireNoMove: true, mode: 'RANGED', advantageDice: 1 },
    }],
    evolvesTo: ['h7_francotirador', 'h6_abanderado'],
  },
  {
    id: 'h4_jinete',
    name: 'Jinete de Vado',
    faction: 'HUMAN',
    tier: 1,
    costGold: 3,
    maxHp: 4,
    move: 5,
    meleeDice: 2,
    rangedDice: 0,
    ascRequired: 4,
    cycleAffinity: 'SUN',
    goodTerrain: 'PLAIN',
    badTerrain: 'FOREST',
    traits: [{
      id: 'carga',
      name: 'Carga',
      description: 'Si movió 3+ hexes, 1 dado melee -> ventaja.',
      trigger: 'ON_BUILD_ATTACK_DICE_POOL',
      config: { requireMinHexesMoved: 3, mode: 'MELEE', advantageDice: 1 },
    }],
    evolvesTo: ['h8_caballero', 'h5_defensor'],
  },

  // ── TIER II ──
  {
    id: 'h5_defensor',
    name: 'Defensor del Bastión',
    faction: 'HUMAN',
    tier: 2,
    maxHp: 7,
    move: 2,
    meleeDice: 3,
    rangedDice: 0,
    ascRequired: 4,
    cycleAffinity: 'SUN',
    goodTerrain: 'CITY',
    badTerrain: 'FOREST',
    traits: [{
      id: 'baluarte',
      name: 'Baluarte',
      description: 'En Ciudad/Fortaleza, reduce en 1 el primer daño de cada ronda.',
      trigger: 'ON_DAMAGE_RECEIVED',
      config: { requireTerrain: ['CITY', 'FORTRESS'], damageReduction: 1, perRound: true },
    }],
    evolvesTo: ['h9_leon'],
  },
  {
    id: 'h6_abanderado',
    name: 'Abanderado Solar',
    faction: 'HUMAN',
    tier: 2,
    maxHp: 5,
    move: 3,
    meleeDice: 2,
    rangedDice: 1,
    ascRequired: 4,
    cycleAffinity: 'SUN',
    goodTerrain: 'CITY',
    badTerrain: 'HILL',
    traits: [{
      id: 'estandarte_solar',
      name: 'Estandarte solar',
      description: 'Primer ataque de humano aliado adyacente por ronda: 1 dado -> ventaja.',
      trigger: 'ON_BUILD_ATTACK_DICE_POOL',
      config: { auraFaction: 'HUMAN', range: 1, advantageDice: 1, firstAttackOnly: true, usesPerRound: 1 },
    }],
    evolvesTo: ['h9_leon'],
  },
  {
    id: 'h7_francotirador',
    name: 'Francotirador de Torre',
    faction: 'HUMAN',
    tier: 2,
    maxHp: 4,
    move: 2,
    meleeDice: 1,
    rangedDice: 3,
    ascRequired: 4,
    cycleAffinity: 'SUN',
    goodTerrain: 'FORTRESS',
    badTerrain: 'FOREST',
    traits: [{
      id: 'posicion_elevada',
      name: 'Posición elevada',
      description: 'Si no se movió: hasta 2 dados ranged -> ventaja.',
      trigger: 'ON_BUILD_ATTACK_DICE_POOL',
      config: { requireNoMove: true, mode: 'RANGED', advantageDice: 2 },
    }],
    evolvesTo: ['h10_mariscal'],
  },
  {
    id: 'h8_caballero',
    name: 'Caballero de Cuña',
    faction: 'HUMAN',
    tier: 2,
    maxHp: 6,
    move: 5,
    meleeDice: 3,
    rangedDice: 0,
    ascRequired: 5,
    cycleAffinity: 'SUN',
    goodTerrain: 'PLAIN',
    badTerrain: 'FOREST',
    traits: [{
      id: 'carga_pesada',
      name: 'Carga pesada',
      description: 'Si movió 3+ hexes: hasta 2 dados melee -> ventaja.',
      trigger: 'ON_BUILD_ATTACK_DICE_POOL',
      config: { requireMinHexesMoved: 3, mode: 'MELEE', advantageDice: 2 },
    }],
    evolvesTo: ['h10_mariscal'],
  },

  // ── TIER III ──
  {
    id: 'h9_leon',
    name: 'León de Bastión',
    faction: 'HUMAN',
    tier: 3,
    maxHp: 8,
    move: 3,
    meleeDice: 3,
    rangedDice: 1,
    cycleAffinity: 'SUN',
    goodTerrain: 'CITY',
    badTerrain: 'FOREST',
    traits: [{
      id: 'muralla_viva',
      name: 'Muralla viva',
      description: 'Primer daño de cada ronda reducido en 1.',
      trigger: 'ON_DAMAGE_RECEIVED',
      config: { damageReduction: 1, perRound: true },
    }],
  },
  {
    id: 'h10_mariscal',
    name: 'Mariscal de la Frontera',
    faction: 'HUMAN',
    tier: 3,
    maxHp: 7,
    move: 4,
    meleeDice: 3,
    rangedDice: 2,
    cycleAffinity: 'SUN',
    goodTerrain: 'PLAIN',
    badTerrain: 'FOREST',
    traits: [{
      id: 'mando_de_campo',
      name: 'Mando de campo',
      description: '1 vez por ronda: un humano aliado adyacente mueve 1 hex.',
      trigger: 'ON_ACTIVATION_START',
      config: { faction: 'HUMAN', range: 1, moveHexes: 1, usesPerRound: 1 },
    }],
  },
];
