import { UnitDefinition } from '../../engine/core/types';

export const ORC_UNITS: UnitDefinition[] = [
  // ── TIER I ──
  {
    id: 'o1_bruto',
    name: 'Bruto del Clan',
    faction: 'ORC',
    tier: 1,
    costGold: 3,
    maxHp: 7,
    move: 3,
    meleeDice: 2,
    rangedDice: 0,
    ascRequired: 4,
    cycleAffinity: 'MOON',
    goodTerrain: 'HILL',
    badTerrain: 'CITY',
    traits: [],
    evolvesTo: ['o5_rompeyelmos', 'o7_estandarte'],
  },
  {
    id: 'o2_saqueador',
    name: 'Saqueador Goblin',
    faction: 'ORC',
    tier: 1,
    costGold: 2,
    maxHp: 4,
    move: 4,
    meleeDice: 1,
    rangedDice: 1,
    ascRequired: 3,
    cycleAffinity: 'MOON',
    goodTerrain: 'HILL',
    badTerrain: 'FORTRESS',
    traits: [{
      id: 'pillaje',
      name: 'Pillaje',
      description: 'La primera captura de la ronda da +1 oro.',
      trigger: 'ON_AFTER_DAMAGE_APPLIED',
      config: { captureBonus: true, goldBonus: 1, usesPerRound: 1 },
    }],
    evolvesTo: ['o6_hostigador', 'o7_estandarte'],
  },
  {
    id: 'o3_lanzador',
    name: 'Lanzador Salvaje',
    faction: 'ORC',
    tier: 1,
    costGold: 3,
    maxHp: 4,
    move: 3,
    meleeDice: 1,
    rangedDice: 2,
    ascRequired: 3,
    cycleAffinity: 'MOON',
    goodTerrain: 'HILL',
    badTerrain: 'FOREST',
    traits: [{
      id: 'contra_herido',
      name: 'Contra herido',
      description: 'Contra dañado: 1 dado ranged -> ventaja.',
      trigger: 'ON_BUILD_ATTACK_DICE_POOL',
      config: { requireTargetDamaged: true, mode: 'RANGED', advantageDice: 1 },
    }],
    evolvesTo: ['o6_hostigador', 'o7_estandarte'],
  },
  {
    id: 'o4_jinete_chatarra',
    name: 'Jinete de Chatarra',
    faction: 'ORC',
    tier: 1,
    costGold: 3,
    maxHp: 5,
    move: 4,
    meleeDice: 2,
    rangedDice: 0,
    ascRequired: 4,
    cycleAffinity: 'MOON',
    goodTerrain: 'PLAIN',
    badTerrain: 'FOREST',
    traits: [{
      id: 'embestida',
      name: 'Embestida',
      description: 'Si movió 2+ hexes: 1 dado melee -> ventaja.',
      trigger: 'ON_BUILD_ATTACK_DICE_POOL',
      config: { requireMinHexesMoved: 2, mode: 'MELEE', advantageDice: 1 },
    }],
    evolvesTo: ['o8_atronador', 'o5_rompeyelmos'],
  },

  // ── TIER II ──
  {
    id: 'o5_rompeyelmos',
    name: 'Rompeyelmos',
    faction: 'ORC',
    tier: 2,
    maxHp: 8,
    move: 3,
    meleeDice: 3,
    rangedDice: 0,
    ascRequired: 5,
    cycleAffinity: 'MOON',
    goodTerrain: 'HILL',
    badTerrain: 'CITY',
    traits: [{
      id: 'golpe_aplastante',
      name: 'Golpe aplastante',
      description: 'Contra dañado: 1 dado melee -> ventaja.',
      trigger: 'ON_BUILD_ATTACK_DICE_POOL',
      config: { requireTargetDamaged: true, mode: 'MELEE', advantageDice: 1 },
    }],
    evolvesTo: ['o9_estampida'],
  },
  {
    id: 'o6_hostigador',
    name: 'Hostigador Sangriento',
    faction: 'ORC',
    tier: 2,
    maxHp: 5,
    move: 5,
    meleeDice: 2,
    rangedDice: 2,
    ascRequired: 4,
    cycleAffinity: 'MOON',
    goodTerrain: 'HILL',
    badTerrain: 'FOREST',
    traits: [{
      id: 'hostigamiento',
      name: 'Hostigamiento',
      description: 'Tras ataque ranged: mueve 1 hex (ignora Traba).',
      trigger: 'ON_AFTER_DAMAGE_APPLIED',
      config: { mode: 'RANGED', moveHexes: 1, ignoresEngagement: true, alwaysAfterAttack: true },
    }],
    evolvesTo: ['o10_ojo_masacre'],
  },
  {
    id: 'o7_estandarte',
    name: 'Estandarte de Guerra',
    faction: 'ORC',
    tier: 2,
    maxHp: 6,
    move: 3,
    meleeDice: 2,
    rangedDice: 1,
    ascRequired: 4,
    cycleAffinity: 'MOON',
    goodTerrain: 'HILL',
    badTerrain: 'FORTRESS',
    traits: [{
      id: 'estandarte_guerra',
      name: 'Estandarte de guerra',
      description: 'Primer ataque de orco aliado adyacente por ronda: 1 dado -> ventaja.',
      trigger: 'ON_BUILD_ATTACK_DICE_POOL',
      config: { auraFaction: 'ORC', range: 1, advantageDice: 1, firstAttackOnly: true, usesPerRound: 1 },
    }],
    evolvesTo: ['o10_ojo_masacre'],
  },
  {
    id: 'o8_atronador',
    name: 'Jinete Atronador',
    faction: 'ORC',
    tier: 2,
    maxHp: 6,
    move: 5,
    meleeDice: 3,
    rangedDice: 0,
    ascRequired: 5,
    cycleAffinity: 'MOON',
    goodTerrain: 'PLAIN',
    badTerrain: 'FOREST',
    traits: [{
      id: 'carga_atronadora',
      name: 'Carga atronadora',
      description: 'Si movió 3+ hexes: hasta 2 dados melee -> ventaja.',
      trigger: 'ON_BUILD_ATTACK_DICE_POOL',
      config: { requireMinHexesMoved: 3, mode: 'MELEE', advantageDice: 2 },
    }],
    evolvesTo: ['o9_estampida'],
  },

  // ── TIER III ──
  {
    id: 'o9_estampida',
    name: 'Señor de la Estampida',
    faction: 'ORC',
    tier: 3,
    maxHp: 9,
    move: 5,
    meleeDice: 4,
    rangedDice: 0,
    cycleAffinity: 'MOON',
    goodTerrain: 'HILL',
    badTerrain: 'FOREST',
    traits: [{
      id: 'estampida',
      name: 'Estampida',
      description: 'Si elimina en melee: mueve 1 hex.',
      trigger: 'ON_UNIT_KILLED',
      config: { mode: 'MELEE', moveHexes: 1 },
    }],
  },
  {
    id: 'o10_ojo_masacre',
    name: 'Ojo de la Masacre',
    faction: 'ORC',
    tier: 3,
    maxHp: 6,
    move: 4,
    meleeDice: 2,
    rangedDice: 3,
    cycleAffinity: 'MOON',
    goodTerrain: 'HILL',
    badTerrain: 'FORTRESS',
    traits: [{
      id: 'sed_de_sangre',
      name: 'Sed de sangre',
      description: 'Primer ataque contra objetivo dañado: hasta 2 dados -> ventaja.',
      trigger: 'ON_BUILD_ATTACK_DICE_POOL',
      config: { requireTargetDamaged: true, firstAttackOnly: true, advantageDice: 2 },
    }],
  },
];
