import { UnitDefinition } from '../../engine/core/types';

export const UNDEAD_UNITS: UnitDefinition[] = [
  // ── TIER I ──
  {
    id: 'n1_guardia_osea',
    name: 'Guardia Ósea',
    faction: 'UNDEAD',
    tier: 1,
    costGold: 2,
    maxHp: 4,
    move: 2,
    meleeDice: 2,
    rangedDice: 0,
    ascRequired: 3,
    cycleAffinity: 'MOON',
    goodTerrain: 'CRYPT',
    badTerrain: 'CITY',
    traits: [{
      id: 'restos_oseos',
      name: 'Restos óseos',
      description: 'Al morir deja restos; si libres al inicio de turno, vuelve con 1 HP.',
      trigger: 'ON_UNIT_KILLED',
      config: { leavesRemains: true, reviveHp: 1 },
    }],
    evolvesTo: ['n5_vanguardia', 'n8_acolito'],
  },
  {
    id: 'n2_zombi',
    name: 'Zombi de la Fosa',
    faction: 'UNDEAD',
    tier: 1,
    costGold: 2,
    maxHp: 5,
    move: 2,
    meleeDice: 2,
    rangedDice: 0,
    ascRequired: 3,
    cycleAffinity: 'MOON',
    goodTerrain: 'CRYPT',
    badTerrain: 'VILLAGE',
    traits: [],
    evolvesTo: ['n5_vanguardia', 'n6_necrofago'],
  },
  {
    id: 'n3_arquera_palida',
    name: 'Arquera Pálida',
    faction: 'UNDEAD',
    tier: 1,
    costGold: 3,
    maxHp: 3,
    move: 3,
    meleeDice: 0,
    rangedDice: 3,
    ascRequired: 3,
    cycleAffinity: 'MOON',
    goodTerrain: 'CRYPT',
    badTerrain: 'FOREST',
    traits: [{
      id: 'flecha_maldita',
      name: 'Flecha maldita',
      description: 'Contra dañado: 1 dado ranged -> ventaja.',
      trigger: 'ON_BUILD_ATTACK_DICE_POOL',
      config: { requireTargetDamaged: true, mode: 'RANGED', advantageDice: 1 },
    }],
    evolvesTo: ['n7_tirador', 'n8_acolito'],
  },
  {
    id: 'n4_ghoul',
    name: 'Ghoul Carroñera',
    faction: 'UNDEAD',
    tier: 1,
    costGold: 3,
    maxHp: 4,
    move: 4,
    meleeDice: 2,
    rangedDice: 0,
    ascRequired: 4,
    cycleAffinity: 'MOON',
    goodTerrain: 'VILLAGE',
    badTerrain: 'FORTRESS',
    traits: [{
      id: 'voracidad',
      name: 'Voracidad',
      description: 'Si inflige daño: cura 1 HP.',
      trigger: 'ON_AFTER_DAMAGE_APPLIED',
      config: { requireDamage: true, selfHeal: 1 },
    }],
    evolvesTo: ['n6_necrofago', 'n5_vanguardia'],
  },

  // ── TIER II ──
  {
    id: 'n5_vanguardia',
    name: 'Vanguardia Ósea',
    faction: 'UNDEAD',
    tier: 2,
    maxHp: 7,
    move: 2,
    meleeDice: 3,
    rangedDice: 0,
    ascRequired: 5,
    cycleAffinity: 'MOON',
    goodTerrain: 'CRYPT',
    badTerrain: 'CITY',
    traits: [{
      id: 'escudo_oseo',
      name: 'Escudo óseo',
      description: 'Primer daño de cada ronda reducido en 1.',
      trigger: 'ON_DAMAGE_RECEIVED',
      config: { damageReduction: 1, perRound: true },
    }],
    evolvesTo: ['n9_tirano'],
  },
  {
    id: 'n6_necrofago',
    name: 'Necrófago Voraz',
    faction: 'UNDEAD',
    tier: 2,
    maxHp: 5,
    move: 5,
    meleeDice: 3,
    rangedDice: 0,
    ascRequired: 4,
    cycleAffinity: 'MOON',
    goodTerrain: 'VILLAGE',
    badTerrain: 'FORTRESS',
    traits: [{
      id: 'devoracion',
      name: 'Devoración',
      description: 'Si elimina: cura 2 HP.',
      trigger: 'ON_UNIT_KILLED',
      config: { selfHeal: 2 },
    }],
    evolvesTo: ['n9_tirano'],
  },
  {
    id: 'n7_tirador',
    name: 'Tirador Pálido',
    faction: 'UNDEAD',
    tier: 2,
    maxHp: 4,
    move: 3,
    meleeDice: 1,
    rangedDice: 4,
    ascRequired: 4,
    cycleAffinity: 'MOON',
    goodTerrain: 'CRYPT',
    badTerrain: 'FOREST',
    traits: [{
      id: 'precision_mortis',
      name: 'Precisión mortis',
      description: 'Contra dañado: 1 dado ranged -> ventaja (se acumula con otras fuentes).',
      trigger: 'ON_BUILD_ATTACK_DICE_POOL',
      config: { requireTargetDamaged: true, mode: 'RANGED', advantageDice: 1, stacks: true },
    }],
    evolvesTo: ['n10_liche'],
  },
  {
    id: 'n8_acolito',
    name: 'Acólito de la Cripta',
    faction: 'UNDEAD',
    tier: 2,
    maxHp: 4,
    move: 3,
    meleeDice: 1,
    rangedDice: 2,
    ascRequired: 4,
    cycleAffinity: 'MOON',
    goodTerrain: 'CRYPT',
    badTerrain: 'FOREST',
    traits: [{
      id: 'maldicion_cripta',
      name: 'Maldición de la cripta',
      description: 'Las unidades dañadas no curan hasta tu siguiente turno.',
      trigger: 'ON_AFTER_DAMAGE_APPLIED',
      config: { appliesHealBlock: true },
    }],
    evolvesTo: ['n10_liche'],
  },

  // ── TIER III ──
  {
    id: 'n9_tirano',
    name: 'Tirano del Osario',
    faction: 'UNDEAD',
    tier: 3,
    maxHp: 9,
    move: 3,
    meleeDice: 4,
    rangedDice: 0,
    cycleAffinity: 'MOON',
    goodTerrain: 'CRYPT',
    badTerrain: 'CITY',
    traits: [{
      id: 'tributo_osario',
      name: 'Tributo del osario',
      description: 'Al eliminar: otro no muerto aliado a 2 hexes cura 1 HP.',
      trigger: 'ON_UNIT_KILLED',
      config: { healAllyFaction: 'UNDEAD', healRange: 2, healAmount: 1 },
    }],
  },
  {
    id: 'n10_liche',
    name: 'Liche del Umbral',
    faction: 'UNDEAD',
    tier: 3,
    maxHp: 5,
    move: 3,
    meleeDice: 2,
    rangedDice: 4,
    cycleAffinity: 'MOON',
    goodTerrain: 'CRYPT',
    badTerrain: 'FOREST',
    traits: [{
      id: 'debilitamiento',
      name: 'Debilitamiento',
      description: 'Enemigo dañado: 1 dado -> desventaja en su próximo ataque.',
      trigger: 'ON_AFTER_DAMAGE_APPLIED',
      config: { requireDamage: true, appliesDisadvantageDebuff: true, disadvantageDice: 1 },
    }],
  },
];
